fos_ck_editor:
  input_sync: true
  default_config: main_config
  configs:
    main_config:
      allowedContent: true
      styleSet: 'custom_style'
      toolbar:
        - { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] }
        - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] }
        - '/'
        - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', '-', 'CopyFormatting', 'RemoveFormat' ] }
        - { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
        - { name: 'insert', items: [ 'Pdf','Table', 'HorizontalRule', 'Smiley', 'SpecialChar'] }
        - { name: 'colors', items: [ 'TextColor', 'BGColor' ] }
        - '/'
        - { name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo' ] }
        - { name: 'tools', items: [ 'Maximize' ] }
        - { name: 'document', items: [ '-', 'Save', 'ExportPdf', 'Preview', '-'] }
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []
