vich_uploader:
    db_driver: orm

    mappings:
        pdf_images:
            uri_prefix: '%pdf_images%'
            upload_destination: '%kernel.project_dir%/public/%pdf_images%'
            delete_on_update: false
            delete_on_remove: false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer